version: '3.8'

services:
  # Apache and PHP service
  web:
    image: php:8-apache
    container_name: php1-apache-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  # MySQL service
  mysql:
    image: mysql:8.0
    networks:
      - my-network
    container_name: mysql1-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=userpassword


  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - my-network
    container_name: phpmyadmin1-container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysql

# Define networks
networks:
  my-network: